apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-demo-app
  namespace: tips-webinar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: my-demo-app
        app: my-demo-app
        version: 'e1b7756'
    spec:
      containers:
      - name: my-demo-app
        image: r.cfcr.io/codefreshdemo/trivial-web:e1b7756
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: codefresh-generated-r.cfcr.io-cfcr-colors
